---
  - name: Install PHP
    apt: 
      name:
        - php
        - php-bcmath
        - php-pdo
        - php-fpm
        - php-mysql
      state: present
    notify:
        - php-fpm start

  - name: Enable services php-fpm
    service: 
      name: php7.4-fpm
      enabled: yes

  - name: Creates directory
    file:
      path: "{{ root }}/{{ hostname_1 }}"
      state: directory
                  
  - name: Add index.html
    template: src=index.html dest={{ root }}/{{ hostname_1 }}/index.html
  - name: Add phpinfo.php
    template: src=phpinfo.php dest={{ root }}/{{ hostname_1 }}/phpinfo.php
 

