---
  - name: Install Nginx
    apt: name=nginx
    notify:
        - nginx start

  - name: Enabled service nginx
    service: 
      name: nginx
      enabled: yes

  - name: Add NGINX cofig
    template: src={{ hostname_1 }}.conf dest=/etc/nginx/conf.d/{{ hostname_1 }}.conf
 
  - name: Create Web Root
    file: path={{ root }}/{{ hostname_1 }}  mode=775 state=directory
    notify:
        - nginx restart

