---
  - name: Install MySQL
    apt: name=default-mysql-server

  - name: start services mysqld
    service: 
      name: mysqld
      state: started 
      enabled: yes


  - name: Copy database
    template: src=database.sql dest=/tmp/database.sql

  - name: Install pip
    apt: name=python3-pip
 
  - name: Install mysql python package
    pip:
      name: PyMySQl


  - name: Start the importing DB
    mysql_db:
      name: restore_db_name
      login_unix_socket: /run/mysqld/mysqld.sock
      state: import
      target: /tmp/database.sql
      login_user: root
