- hosts: server-1

  pre_tasks:
  - name: Put SELinux in permissive mode
    ansible.posix.selinux:
      policy: targeted
      state: permissive
  - name: Upgrade all packages
    yum: name=* state=latest
  - name: Install optional software
    yum: 
      name:
        - mc
        - nano
        - net-tools
      state: present

  - name: Reboot
    shell: nohup bash -c "sleep 2s && shutdown -r now" &
    async: 0
    poll: 0
    ignore_errors: true
    register: reboot



  - name: wait for the server to restart
    local_action: wait_for host={{ inventory_hostname }}
      port=22
      delay=30
      timeout=300
    when: reboot.changed

    
  roles:
    - nginx
    - php
    - firewalld
    - mysql
