- hosts: server-1

  pre_tasks:
  - name: Upgrade all packages
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Install optional software
    apt:
      name:
        - mc
        - nano
      state: present

  - name: Reboot
    shell: nohup bash -c "sleep 2s && shutdown -r now" &
    async: 0
    poll: 0
    ignore_errors: true
    register: reboot

  - name: wait for the server to restart
    local_action: wait_for host={{ inventory_hostname }}
      port=22
      delay=30
      timeout=300
    when: reboot.changed

    
  roles:
    - nginx
    - php
    - mysql
